/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        PaymentMethod visa = new CreditCard();
        PaymentMethod paypal = new Paypal();
        PaymentMethod bank = new BankTransfer();
        PaymentGateway paymentGateway = new PaymentGateway();

        paymentGateway.executePaymentWith(85, visa);
        paymentGateway.executePaymentWith(385, visa);
        paymentGateway.executePaymentWith(30, paypal);
        paymentGateway.executePaymentWith(285, bank);
    }
}
