/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        StockBroker broker = new StockBroker();

        broker.addObserver(new Bank("CaixaBank"));
        broker.addObserver(new Person("Pepito"));
        broker.addObserver(new Bank("SabadelL"));
        broker.addObserver(new Bank("ARQUIA"));

        broker.setStockPrice("Microsoft", 123.34);
        broker.setStockPrice("Nvidia", 100.10);
        broker.setStockPrice("Microsoft", 123.34);
        broker.setStockPrice("Alphabet", 230.22);
        broker.setStockPrice("Apple", 14.23);

    }
}
