/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Main {

    public static void main(String[] args) {
        Pizza pizza;

        pizza = new PizzaChef(new HawaiianPizzaBuilder())
                .dough(Pizza.Dough.THIN_CRUST)
                .size(Pizza.Size.LARGE)
                .make();
        System.out.println(pizza);

        pizza = new PizzaChef(new VegetarianPizzaBuilder())
                .dough(Pizza.Dough.FLUFFY)
                .size(Pizza.Size.MINI)
                .make();
        System.out.println(pizza);

        pizza = new PizzaChef(new CheesePizzaBuilder())
                .dough(Pizza.Dough.NY_STYLE)
                .size(Pizza.Size.EXTRA_LARGE)
                .make();
        System.out.println(pizza);

        pizza = new PizzaChef(new MediterraneanPizzaBuilder())
                .dough(Pizza.Dough.GLUTEN_FREE)
                .size(Pizza.Size.MEDIUM)
                .make();
        System.out.println(pizza);

    }
}
